### ISSUE TITLE
update README.md

### ISSUE THREAD

**Issue by bhupendpatil** [Shubham3016/Python-Bootcamp-#1]
It should be 

`This Repository Contains Python programming for Beginners which is very helpful for those who are willing to Learn Python programming from scratch.`

instead of 

`This Repository Contains Python programming for Beginners which is very helpful for those who are Willing to Learn R programming from scratch.`

**Comment by bhupendpatil** [comment]
[![GitHub Streak](http://github-readme-streak-stats.herokuapp.com?user=bhupendpatil&theme=dark&hide_border=true)](https://git.io/streak-stats)

**Comment by Shubham3016** [comment]
Thank you
done
changes

**Comment by bhupendpatil** [comment]
Great 😄
